//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Brawler.Simulation;
using Brawler.Input.Packets;


namespace Blackboard.Demo.Console
{
	public class CharacterInfo
	{
		public PlayerInfo Previous {get;set;}
		public PlayerInfo Current {get;set;}
		public ControllerState Input {get;set;}
	}
}

