//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace BirdNest.Nodes
{
	public class BlackboardAction<T> : Action, IBlackboardNode<T>
		where T : class
	{
		private Func<T, Result> mAction;

		public BlackboardAction (Func<T, Result> func)
		{
			this.mAction = func;
		}

		#region IBlackboardNode implementation

		public Blackboard<T> Board
		{
			get;
			set;
		}

		#endregion

		#region implemented abstract members of Leaf

		public override Result DoStuff ()
		{
			return this.mAction(this.Board.Context);
		}

		#endregion
	}
}

