//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BirdNest.Nodes
{
	public class BlackboardEntireTreeNode<T> : Decorator, IEntireTreeNode, IBlackboardNode<T>
		where T : class
	{
		#region IBlackboardNode implementation

		public Blackboard<T> Board
		{
			get ;
			set ;
		}

		#endregion

		public BlackboardEntireTreeNode (Tree treeNodes)
		{
			this.ExistingTree = treeNodes;
		}

		#region IEntireTreeNode implementation

		public Tree ExistingTree
		{
			get;
			set;
		}

		#endregion

		#region implemented abstract members of Decorator

		public override INodeExaminer CreateNodeExaminer ()
		{
			return new EntireTreeNodeExaminer<BlackboardEntireTreeNode<T>>(this);
		}

		#endregion
	}
}

