//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BirdNest.Nodes
{
	public interface IBlackboardParameter
	{
		void Assign(INode node);
		void Assign<TParent>(IBlackboardNode<TParent> node) where TParent : class;
	}
}

