//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BirdNest.Nodes
{
	public interface IBlackBoardTreeBuilder<T> where T : class
	{
		ITreeBuilder TreeBuilder {get;set;}		
		Tree Build ();
	}

}

