//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace bt
{
	public class PersistentBlackboardContext<T> : Decorator where T : class
	{
		public T Context { get; set; }

		public PersistentBlackboardContext (T item)
		{

		}

		#region implemented abstract members of Decorator

		public override INodeExaminer CreateNodeExaminer ()
		{
			return new BlackboardNodeExaminer<T>(this);
		}

		#endregion
	}
}

