//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace BirdNest.Nodes
{
	public class StaticParameter<T> : IBlackboardParameter
		where T : class
	{
		public Blackboard<T> Board { get; set; }

		public StaticParameter (Blackboard<T> board)
		{
			this.Board = board;
		}

		public void Assign(INode node)
		{
			if (node is IBlackboardNode<T>)
			{
				IBlackboardNode<T> specificNode = node as IBlackboardNode<T>;
				specificNode.Board = this.Board;
			}
		}

		public void Assign<TParent> (IBlackboardNode<TParent> node) where TParent : class
		{
			if (this is StaticParameter<TParent>) {
				node.Board = this.Board as Blackboard<TParent>;
			}
		}
	}
}

