//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace BirdNest.Nodes
{
	public class TransistentBlackboard<T> : Blackboard<T>
		where T : class
	{
		private Func<T> mFunction;

		public TransistentBlackboard (System.Func<T> func)
		{
			this.mFunction = func;
		}

		public void Reset()
		{
			Context = this.mFunction();
		}
	}
}

